"""
Executive Briefing Engine — Decision Tracker
CORE-010E

Derives pending decisions from existing intelligence data.
Each decision requires owner resolution.
"""

from typing import Any, List, Mapping

from .models import (
    PRIORITY_CRITICAL,
    PRIORITY_HIGH,
    PRIORITY_LOW,
    PRIORITY_MEDIUM,
    ExecutiveDecision,
)


class ExecutiveDecisionTracker:
    """
    Derives pending decisions that require owner action from snapshot data.

    Decisions are generated by examining:
    - Development state blocking conditions
    - Architecture extension choices
    - Canonical roadmap forks
    - Integration readiness gates
    """

    def extract(self, snapshot: Mapping[str, Any]) -> List[ExecutiveDecision]:
        """Return list of pending decisions derived from snapshot."""
        decisions: List[ExecutiveDecision] = []
        counter = [0]

        def next_id() -> str:
            counter[0] += 1
            return f"DEC-{counter[0]:03d}"

        state = snapshot.get("state", {})
        integrations = snapshot.get("integrations", {})
        context = snapshot.get("current_context", {})

        decisions.extend(self._blocked_task_decisions(next_id, state))
        decisions.extend(self._next_core_decision(next_id, integrations, context))
        decisions.extend(self._integration_gate_decisions(next_id, integrations))
        decisions.extend(self._pr_merge_decisions(next_id, state))

        return decisions

    # ------------------------------------------------------------------
    # Blocked task decisions
    # ------------------------------------------------------------------

    def _blocked_task_decisions(
        self, next_id, state: Mapping[str, Any]
    ) -> List[ExecutiveDecision]:
        decisions: List[ExecutiveDecision] = []
        workspace = state.get("workspace_state", {})
        blocked_tasks = workspace.get("blocked_tasks", [])

        if isinstance(blocked_tasks, list) and blocked_tasks:
            task_list = ", ".join(str(t) for t in blocked_tasks[:3])
            decisions.append(ExecutiveDecision(
                id=next_id(),
                title="Resolve or de-prioritize blocked tasks",
                description=(
                    f"{len(blocked_tasks)} tasks are blocked: {task_list}. "
                    "The owner must decide whether to unblock, reassign, or de-prioritize them."
                ),
                options=(
                    "Unblock by resolving dependency or constraint",
                    "Reassign to another executor",
                    "De-prioritize and move to backlog",
                    "Cancel task entirely",
                ),
                recommended_option="Unblock by resolving dependency or constraint",
                impact="Restores development velocity and unblocks downstream work.",
                urgency=PRIORITY_HIGH,
                context=(
                    f"Blocked tasks: {blocked_tasks[:5]}"
                ),
            ))

        return decisions

    # ------------------------------------------------------------------
    # Next CORE decision
    # ------------------------------------------------------------------

    def _next_core_decision(
        self, next_id, integrations: Mapping[str, Any], context: Mapping[str, Any]
    ) -> List[ExecutiveDecision]:
        decisions: List[ExecutiveDecision] = []
        semantic = integrations.get("semantic_repository_intelligence", {})
        next_core = semantic.get("analysis", {}).get("next_core", "")

        current_recommendation = context.get("current_recommendation", "")

        if next_core and next_core != current_recommendation:
            decisions.append(ExecutiveDecision(
                id=next_id(),
                title=f"Confirm next CORE module: {next_core}",
                description=(
                    f"Semantic analysis recommends implementing {next_core} as the "
                    f"next CORE module, but the current recommendation is "
                    f"'{current_recommendation or 'unset'}'."
                ),
                options=(
                    f"Proceed with {next_core} as recommended by semantic analysis",
                    f"Keep current recommendation: {current_recommendation}" if current_recommendation else "Set a different next CORE module",
                    "Defer decision and continue with current work",
                ),
                recommended_option=f"Proceed with {next_core} as recommended by semantic analysis",
                impact="Determines the next major development capability.",
                urgency=PRIORITY_MEDIUM,
                context=(
                    f"Semantic recommendation: {next_core}. "
                    f"Current context recommendation: {current_recommendation or 'none'}."
                ),
            ))

        return decisions

    # ------------------------------------------------------------------
    # Integration gate decisions
    # ------------------------------------------------------------------

    def _integration_gate_decisions(
        self, next_id, integrations: Mapping[str, Any]
    ) -> List[ExecutiveDecision]:
        decisions: List[ExecutiveDecision] = []
        canon = integrations.get("canonical_intelligence", {})
        coverage = float(canon.get("overall_coverage", 100.0))
        drift = int(canon.get("drift_findings", 0))

        if coverage < 50.0 or drift > 5:
            decisions.append(ExecutiveDecision(
                id=next_id(),
                title="Decide on canonical quality gate enforcement",
                description=(
                    "Canonical health metrics are below thresholds "
                    f"(coverage={coverage:.1f}%, drift={drift}). "
                    "The owner must decide whether to enforce a quality gate."
                ),
                options=(
                    "Enforce quality gate: halt new features until metrics recover",
                    "Set target timeline for metric recovery",
                    "Accept current state and continue",
                ),
                recommended_option="Enforce quality gate: halt new features until metrics recover",
                impact="Prevents further metric deterioration while enforcing quality standards.",
                urgency=PRIORITY_HIGH if drift > 5 else PRIORITY_MEDIUM,
                context=(
                    f"canonical_coverage={coverage:.1f}%, drift_findings={drift}"
                ),
            ))

        return decisions

    # ------------------------------------------------------------------
    # PR merge decisions
    # ------------------------------------------------------------------

    def _pr_merge_decisions(
        self, next_id, state: Mapping[str, Any]
    ) -> List[ExecutiveDecision]:
        decisions: List[ExecutiveDecision] = []
        review = state.get("review_state", {})
        open_prs = review.get("open_prs", [])

        if isinstance(open_prs, list) and len(open_prs) > 3:
            decisions.append(ExecutiveDecision(
                id=next_id(),
                title=f"Prioritize pull request queue ({len(open_prs)} open PRs)",
                description=(
                    f"{len(open_prs)} pull requests are open.  "
                    "The owner must decide the merge order and priority."
                ),
                options=(
                    "Merge in order of creation (FIFO)",
                    "Merge critical path PRs first",
                    "Request additional reviews before merging",
                    "Close stale PRs and consolidate",
                ),
                recommended_option="Merge critical path PRs first",
                impact="Clears integration debt and reduces merge conflict probability.",
                urgency=PRIORITY_MEDIUM,
                context=(
                    f"open_pull_requests={open_prs[:5]}"
                ),
            ))

        return decisions
