"""
Executive Briefing Engine — Recommendation Engine
CORE-010C

Generates evidence-based executive recommendations from existing
intelligence data.  No analysis is re-run.  All recommendations are
derived from snapshot data produced by DevelopmentStateManager and
lower CORE engines.
"""

from typing import Any, Dict, List, Mapping

from .models import (
    PRIORITY_CRITICAL,
    PRIORITY_HIGH,
    PRIORITY_LOW,
    PRIORITY_MEDIUM,
    ExecutiveRecommendation,
    ExecutiveRisk,
    RISK_ARCHITECTURE,
    RISK_CANONICAL_DRIFT,
    RISK_MISSING_COMPONENTS,
    RISK_BROKEN_DEPENDENCIES,
    RISK_REGRESSION,
    RISK_TECHNICAL_DEBT,
    SEVERITY_CRITICAL,
    SEVERITY_HIGH,
)


# Sentinel values from the development state models that represent "not set"
_EMPTY_SENTINELS = frozenset({"", "UNSPECIFIED", "None", "null", "N/A"})


def _is_set(value) -> bool:
    """Return True if the value is a meaningful (non-sentinel) string."""
    return bool(value) and str(value).strip() not in _EMPTY_SENTINELS

_PRIORITY_ORDER = {
    PRIORITY_CRITICAL: 0,
    PRIORITY_HIGH: 1,
    PRIORITY_MEDIUM: 2,
    PRIORITY_LOW: 3,
}


class ExecutiveRecommendationEngine:
    """
    Derives evidence-based executive recommendations from snapshot data.

    Recommendations are generated by examining:
    - Canonical intelligence results (coverage, compliance, drift)
    - Architecture graph analysis
    - Executable repository intelligence
    - Development state (blocked tasks, open PRs)
    - Risk findings from ExecutiveRiskAnalyzer

    Every recommendation carries: priority, impact, confidence, required_effort,
    dependencies, affected_components, reasoning, and evidence.
    """

    def generate(
        self,
        snapshot: Mapping[str, Any],
        risks: List[ExecutiveRisk],
    ) -> List[ExecutiveRecommendation]:
        """Return deduplicated, priority-sorted recommendations."""
        recs: List[ExecutiveRecommendation] = []
        counter = [0]

        def next_id() -> str:
            counter[0] += 1
            return f"REC-{counter[0]:03d}"

        integrations = snapshot.get("integrations", {})
        state = snapshot.get("state", {})
        context = snapshot.get("current_context", {})

        recs.extend(self._canonical_recommendations(next_id, integrations))
        recs.extend(self._architecture_recommendations(next_id, integrations))
        recs.extend(self._development_state_recommendations(next_id, state, context))
        recs.extend(self._risk_driven_recommendations(next_id, risks))
        recs.extend(self._semantic_recommendations(next_id, integrations))

        if not recs:
            recs.append(self._healthy_repository_recommendation(next_id))

        return self._sort_recommendations(recs)

    # ------------------------------------------------------------------
    # Canonical intelligence recommendations
    # ------------------------------------------------------------------

    def _canonical_recommendations(
        self, next_id, integrations: Mapping[str, Any]
    ) -> List[ExecutiveRecommendation]:
        recs: List[ExecutiveRecommendation] = []
        canon = integrations.get("canonical_intelligence", {})
        coverage = float(canon.get("overall_coverage", 100.0))
        compliance = float(canon.get("overall_compliance", 100.0))
        drift = int(canon.get("drift_findings", 0))
        batches = int(canon.get("batches", 0))
        canon_docs = int(canon.get("canonical_documents", 0))

        if drift > 0:
            priority = PRIORITY_CRITICAL if drift > 5 else PRIORITY_HIGH
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title="Resolve canonical drift findings",
                description=(
                    f"There are {drift} canonical drift findings that indicate "
                    "the implementation has diverged from its specification."
                ),
                priority=priority,
                impact="Restores alignment between specification and implementation.",
                confidence=0.95,
                required_effort="medium" if drift <= 3 else "high",
                dependencies=(),
                affected_components=(),
                reasoning=(
                    "Canonical drift findings signal that the codebase no longer matches "
                    "its canonical documentation.  Left unresolved, this leads to "
                    "compounding inconsistencies and increases maintenance cost."
                ),
                evidence=(f"canonical_drift_findings={drift}",),
            ))

        if coverage < 80.0:
            priority = PRIORITY_CRITICAL if coverage < 50.0 else PRIORITY_HIGH
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=f"Improve canonical coverage from {coverage:.1f}% to ≥80%",
                description=(
                    f"Canonical coverage is {coverage:.1f}%, below the target of 80%. "
                    "Implement missing canonical modules to close the gap."
                ),
                priority=priority,
                impact="Ensures all canonical specifications have corresponding implementations.",
                confidence=0.90,
                required_effort="high",
                dependencies=(),
                affected_components=(),
                reasoning=(
                    "Low canonical coverage means significant portions of the system "
                    "specification lack implementation.  This increases project risk."
                ),
                evidence=(f"overall_coverage={coverage:.1f}%",),
            ))

        if compliance < 80.0:
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=f"Improve canonical compliance from {compliance:.1f}% to ≥80%",
                description=(
                    f"Canonical compliance is {compliance:.1f}%, below the target of 80%."
                ),
                priority=PRIORITY_HIGH,
                impact="Brings implementation into compliance with canonical specification.",
                confidence=0.85,
                required_effort="medium",
                dependencies=(),
                affected_components=(),
                reasoning=(
                    "Low compliance means existing implementations do not conform to "
                    "their canonical specifications."
                ),
                evidence=(f"overall_compliance={compliance:.1f}%",),
            ))

        if batches > 3:
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=f"Execute pending canonical batches ({batches} remaining)",
                description=(
                    f"{batches} canonical implementation batches are pending execution."
                ),
                priority=PRIORITY_MEDIUM,
                impact="Reduces implementation debt and advances canonical coverage.",
                confidence=0.80,
                required_effort="medium",
                dependencies=(),
                affected_components=(),
                reasoning=(
                    f"{batches} batches remain unexecuted.  Processing them will improve "
                    "canonical coverage and compliance metrics."
                ),
                evidence=(f"pending_batches={batches}",),
            ))

        return recs

    # ------------------------------------------------------------------
    # Architecture recommendations
    # ------------------------------------------------------------------

    def _architecture_recommendations(
        self, next_id, integrations: Mapping[str, Any]
    ) -> List[ExecutiveRecommendation]:
        recs: List[ExecutiveRecommendation] = []
        arch = (
            integrations
            .get("semantic_repository_intelligence", {})
            .get("analysis", {})
            .get("architecture_graph", {})
        )
        arch_risks = arch.get("risks", [])
        hotspots = arch.get("hotspots", [])
        extension_points = arch.get("extension_points", [])

        if arch_risks:
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=f"Resolve architecture risks ({len(arch_risks)} detected)",
                description=(
                    f"{len(arch_risks)} architectural risks detected in the semantic graph."
                ),
                priority=PRIORITY_HIGH,
                impact="Reduces structural fragility and future maintenance cost.",
                confidence=0.88,
                required_effort="high",
                dependencies=(),
                affected_components=tuple(hotspots[:3]),
                reasoning=(
                    "Architecture risks identified by semantic analysis indicate structural "
                    "weaknesses that compound over time."
                ),
                evidence=tuple(str(r) for r in arch_risks[:3]),
            ))

        if hotspots and len(hotspots) > 3:
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=f"Decompose high-coupling hotspots ({len(hotspots)} detected)",
                description=(
                    f"{len(hotspots)} high-coupling hotspots increase change risk."
                ),
                priority=PRIORITY_MEDIUM,
                impact="Reduces coupling, improves testability and maintainability.",
                confidence=0.75,
                required_effort="high",
                dependencies=(),
                affected_components=tuple(hotspots[:5]),
                reasoning=(
                    "Hotspot modules are heavily depended upon.  Decomposing them "
                    "reduces the blast radius of future changes."
                ),
                evidence=tuple(hotspots[:3]),
            ))

        if not extension_points:
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title="Define architecture extension points",
                description=(
                    "No extension points detected in the architecture graph.  "
                    "Define explicit extension points to guide future integrations."
                ),
                priority=PRIORITY_LOW,
                impact="Enables structured extension without touching core modules.",
                confidence=0.65,
                required_effort="medium",
                dependencies=(),
                affected_components=(),
                reasoning=(
                    "Extension points make the architecture explicitly extensible.  "
                    "Their absence increases the risk of ad-hoc coupling."
                ),
                evidence=("extension_points=[]",),
            ))

        return recs

    # ------------------------------------------------------------------
    # Development state recommendations
    # ------------------------------------------------------------------

    def _development_state_recommendations(
        self, next_id, state: Mapping[str, Any], context: Mapping[str, Any]
    ) -> List[ExecutiveRecommendation]:
        recs: List[ExecutiveRecommendation] = []
        workspace = state.get("workspace_state", {})
        review = state.get("review_state", {})

        blocked_tasks = workspace.get("blocked_tasks", [])
        if isinstance(blocked_tasks, list) and blocked_tasks:
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=f"Unblock stalled work items ({len(blocked_tasks)} blocked)",
                description=(
                    f"{len(blocked_tasks)} tasks are currently blocked and require attention."
                ),
                priority=PRIORITY_HIGH,
                impact="Restores development velocity by clearing blockers.",
                confidence=0.90,
                required_effort="low",
                dependencies=(),
                affected_components=tuple(blocked_tasks[:3]),
                reasoning=(
                    "Blocked tasks directly reduce throughput.  "
                    "Each unresolved blocker stalls downstream work."
                ),
                evidence=tuple(blocked_tasks[:3]),
            ))

        open_prs = review.get("open_prs", [])
        if isinstance(open_prs, list) and len(open_prs) > 2:
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=f"Review and merge open pull requests ({len(open_prs)} open)",
                description=(
                    f"{len(open_prs)} pull requests are open.  "
                    "Reduce the review queue to prevent integration drift."
                ),
                priority=PRIORITY_MEDIUM,
                impact="Reduces integration risk and keeps the main branch current.",
                confidence=0.80,
                required_effort="low",
                dependencies=(),
                affected_components=tuple(open_prs[:3]),
                reasoning=(
                    "Open PRs accumulate merge conflicts and context loss over time.  "
                    "Processing them promptly keeps integration overhead low."
                ),
                evidence=(f"open_pull_requests={len(open_prs)}",),
            ))

        current_recommendation = context.get("current_recommendation", "")
        if _is_set(current_recommendation):
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=f"Execute current recommendation: {current_recommendation}",
                description=(
                    f"The development state recommends executing: {current_recommendation}."
                ),
                priority=PRIORITY_HIGH,
                impact="Advances planned development work.",
                confidence=0.85,
                required_effort="medium",
                dependencies=(),
                affected_components=(),
                reasoning=(
                    "The active canonical recommendation represents the highest-value "
                    "next step derived from all accumulated intelligence."
                ),
                evidence=(f"current_recommendation={current_recommendation}",),
            ))

        return recs

    # ------------------------------------------------------------------
    # Risk-driven recommendations
    # ------------------------------------------------------------------

    def _risk_driven_recommendations(
        self, next_id, risks: List[ExecutiveRisk]
    ) -> List[ExecutiveRecommendation]:
        recs: List[ExecutiveRecommendation] = []
        critical_risks = [r for r in risks if r.severity == SEVERITY_CRITICAL]
        high_risks = [r for r in risks if r.severity == SEVERITY_HIGH]

        if critical_risks:
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=f"Address critical risks immediately ({len(critical_risks)} critical)",
                description=(
                    f"{len(critical_risks)} critical risks require immediate attention "
                    "before any other development activity."
                ),
                priority=PRIORITY_CRITICAL,
                impact="Prevents systemic failures and data loss.",
                confidence=0.98,
                required_effort="high",
                dependencies=(),
                affected_components=tuple(
                    comp
                    for r in critical_risks
                    for comp in r.affected_components
                )[:5],
                reasoning=(
                    "Critical risks left unaddressed will cascade into systemic failures.  "
                    "They must be resolved before any new development work proceeds."
                ),
                evidence=tuple(r.title for r in critical_risks[:3]),
            ))

        if len(high_risks) > 3:
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=f"Schedule risk mitigation sprint ({len(high_risks)} high risks)",
                description=(
                    f"{len(high_risks)} high-severity risks warrant a dedicated "
                    "mitigation sprint."
                ),
                priority=PRIORITY_HIGH,
                impact="Systematically reduces risk backlog and improves system stability.",
                confidence=0.82,
                required_effort="high",
                dependencies=(),
                affected_components=(),
                reasoning=(
                    "A large backlog of high risks compounds into technical debt.  "
                    "A focused sprint prevents further accumulation."
                ),
                evidence=(f"high_severity_risks={len(high_risks)}",),
            ))

        return recs

    # ------------------------------------------------------------------
    # Semantic intelligence recommendations
    # ------------------------------------------------------------------

    def _semantic_recommendations(
        self, next_id, integrations: Mapping[str, Any]
    ) -> List[ExecutiveRecommendation]:
        recs: List[ExecutiveRecommendation] = []
        semantic = integrations.get("semantic_repository_intelligence", {})
        analysis = semantic.get("analysis", {})
        top_rec = analysis.get("top_recommendation", {})
        next_core = analysis.get("next_core", "")

        if top_rec.get("title"):
            priority_map = {"critical": PRIORITY_CRITICAL, "high": PRIORITY_HIGH, "medium": PRIORITY_MEDIUM, "low": PRIORITY_LOW}
            raw_priority = str(top_rec.get("priority", "medium")).lower()
            priority = priority_map.get(raw_priority, PRIORITY_MEDIUM)
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=top_rec["title"],
                description=(
                    f"Semantic analysis top recommendation: {top_rec['title']} "
                    f"(ID: {top_rec.get('id', 'N/A')})."
                ),
                priority=priority,
                impact="Improves semantic architecture quality.",
                confidence=0.78,
                required_effort="medium",
                dependencies=(),
                affected_components=(),
                reasoning=(
                    "Derived from semantic repository intelligence analysis of the "
                    "import graph, call graph, and architecture graph."
                ),
                evidence=(f"semantic_recommendation_id={top_rec.get('id', 'N/A')}",),
            ))

        if next_core:
            recs.append(ExecutiveRecommendation(
                id=next_id(),
                title=f"Implement {next_core} as the next CORE module",
                description=(
                    f"Semantic analysis suggests {next_core} as the next CORE "
                    "implementation."
                ),
                priority=PRIORITY_MEDIUM,
                impact="Advances the AI CTO intelligence layer.",
                confidence=0.72,
                required_effort="high",
                dependencies=(),
                affected_components=(),
                reasoning=(
                    "CORE module suggestions are derived from current repository "
                    "intelligence gaps and architectural extension points."
                ),
                evidence=(f"suggested_next_core={next_core}",),
            ))

        return recs

    # ------------------------------------------------------------------
    # Fallback for healthy repos
    # ------------------------------------------------------------------

    def _healthy_repository_recommendation(self, next_id) -> ExecutiveRecommendation:
        return ExecutiveRecommendation(
            id=next_id(),
            title="Continue planned development roadmap",
            description=(
                "All health metrics are within acceptable ranges.  "
                "Continue executing the planned development roadmap."
            ),
            priority=PRIORITY_LOW,
            impact="Maintains development momentum.",
            confidence=0.70,
            required_effort="medium",
            dependencies=(),
            affected_components=(),
            reasoning=(
                "No critical issues detected.  The repository is in a healthy state "
                "and development should continue as planned."
            ),
            evidence=("all_health_checks_passed",),
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _sort_recommendations(
        self, recs: List[ExecutiveRecommendation]
    ) -> List[ExecutiveRecommendation]:
        return sorted(
            recs,
            key=lambda r: (_PRIORITY_ORDER.get(r.priority, 9), -r.confidence),
        )
